version: 2
updates:
  # app
  - package-ecosystem: "pub"
    directory: "app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "pub"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      app:
        patterns:
          - "*"

  #server
  - package-ecosystem: "nuget"
    directory: "server"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      server:
        patterns:
          - "*"

  # devops
  - package-ecosystem: "nuget"
    directory: "devops"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      devops:
        patterns:
          - "*"

  # GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "build"
      include: "scope"
