receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318

exporters:
  debug:
    # (detailed|normal|basic)
    verbosity: basic
  otlphttp/axiom:
    compression: gzip
    endpoint: https://api.axiom.co
    headers:
      authorization: "Bearer {{AXIOM_TOKEN}}"
      x-axiom-dataset: "{{AXIOM_DATASET}}"

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  batch:

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, otlphttp/axiom]
