name: emma
description: Open source energy management
publish_to: none
version: 1.0.0-alpha.1
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  chopper: ^8.0.0
  confirm_dialog: ^1.0.3
  cupertino_icons: ^1.0.6
  desktop_window: ^0.4.0
  freezed: ^2.5.0
  get_it: ^7.6.8
  intl: ^0.19.0
  json_annotation: ^4.8.0
  logging: ^1.2.0
  oidc_default_store: ^0.2.0+8
  oidc: ^0.5.2
  package_info_plus: ^8.0.0
  signals: ^5.2.0
  url_launcher: ^6.2.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  chopper_generator: ^8.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.10.4
flutter:
  uses-material-design: true
  assets:
    - assets/isometric-house-collection_1146735_brown.webp
  fonts:
    - family: FiraSans
      fonts:
        - asset: fonts/FiraSans-Regular.ttf
    - family: materialdesignicons_webfont
      fonts:
        - asset: fonts/materialdesignicons-webfont.ttf
