volumes:
  keycloak_database_data:
  backend_database_data:
  lavinmq_data:

secrets:
  keycloak-env:
    file: ./keycloak/.env

services:
  keycloak:
    image: keycloak:local
    build:
      context: ../../keycloak
    depends_on:
      - keycloak-database
    ports:
      - 5001:8080
    secrets:
      - source: keycloak-env
        target: .env
    command: start-dev

  keycloak-config:
    image: quay.io/adorsys/keycloak-config-cli:latest-24.0.1
    depends_on:
      - keycloak
    volumes:
      - ./keycloak/config:/config:ro
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_AVAILABILITYCHECK_ENABLED=true
      - IMPORT_FILES_LOCATIONS=/config/*
      - IMPORT_VALIDATE=true

  keycloak-database:
    image: postgres:16
    volumes:
      - keycloak_database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  backend-database:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - backend_database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  adminer:
    image: adminer:latest
    ports:
      - 5002:8080
    environment:
      - ADMINER_DEFAULT_SERVER=backend-database

  lavinmq:
    image: cloudamqp/lavinmq
    volumes:
      - lavinmq_data:/var/lib/lavinmq
    ports:
      - 5672:5672
      - 5003:15672
