networks:
  messages:

volumes:
  rabbitmq_data:

secrets:
  server_secrets:
    file: ./secrets.json

services:
  server:
    # x-release-please-start-version
    image: ghcr.io/opencleanenergy/openems-server:1.0.0-alpha.44
    # x-release-please-end
    networks:
      - default
      - messages
    secrets:
      - source: server_secrets
        target: secrets.json
    env_file:
      - ../common/.env
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    restart: on-failure

  rabbitmq:
    image: rabbitmq:4-alpine
    # IMPORTANT: The hostname must not changed to persist the data between container restarts
    hostname: rabbitmq
    networks:
      - messages
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ../common/.env
    restart: on-failure

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml:ro
    env_file:
      - ../common/.env
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
