- name: 📤 Copy files to remote host
  become: true
  ansible.builtin.copy:
    src: /tmp/emma/ansible/rendered/
    dest: /var/lib/emma/
    directory_mode: "755"
    mode: "644"
    backup: true

- name: 🚀 Launch docker compose stack
  ansible.builtin.command:
    cmd: bash compose-up.sh
    chdir: /var/lib/emma
