- name: 📂 Generate the destination directory
  become: true
  ansible.builtin.file:
    path: /var/lib/emma
    state: directory
    mode: 0755

- name: 📤 Copy files to remote host
  become: true
  ansible.builtin.copy:
    src: /tmp/emma/ansible/rendered/
    dest: /var/lib/emma/
    mode: 0644
    backup: true

- name: 🚀 Launch docker compose stack
  ansible.builtin.command:
    cmd: bash compose-up.sh
    chdir: /var/lib/emma
