include:
  - ./keycloak/compose.yaml
  - ./server/compose.yaml
  - ./web-app/compose.yaml

volumes:
  proxy_data:
  proxy_config:

services:
  proxy:
    image: caddy:2
    volumes:
      - proxy_data:/data # Certs etc.
      - proxy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    env_file:
      - ./common/.env
    restart: on-failure
