volumes:
  proxy_data:
  proxy_config:
  keycloak_database_data:

secrets:
  keycloak-env:
    file: ./keycloak/.env

services:
  proxy:
    image: caddy:2
    volumes:
      - proxy_data:/data
      - proxy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443

  whoami:
    image: traefik/whoami

  keycloak:
    image: keycloak:local
    build:
      context: ../
    depends_on:
      - keycloak-database
    secrets:
      - source: keycloak-env
        target: .env
    command: start

  keycloak-config:
    image: quay.io/adorsys/keycloak-config-cli:latest-24.0.1
    depends_on:
      - keycloak
    volumes:
      - ./keycloak/config:/config:ro
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_AVAILABILITYCHECK_ENABLED=true
      - IMPORT_FILES_LOCATIONS=/config/*
      - IMPORT_VALIDATE=true

  keycloak-database:
    image: postgres:15-alpine
    volumes:
      - keycloak_database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
