name: 🚀 Pipeline

on:
  push:
    branches: ["**"]

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-server:
    name: 🚂 Build server
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: 🏞️ Setup environment
        uses: ./.github/actions/setup-environment
        with:
          dotnet: true

      - name: 🛠️ Build
        run: just target build:build

  build-app:
    name: 📱 Build app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: 🏞️ Setup environment
        uses: ./.github/actions/setup-environment
        with:
          flutter: true

      - name: 🏗 Restore dependencies
        run: just pub-get

      - name: 🎨 Analyze
        run: just analyze

      - name: 🛠️ Build
        run: just build appbundle

  release-please:
    name: ✨ Release Please
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      created: ${{ steps.release.outputs.release_created }}
      server-created: ${{ steps.release.outputs.server--release_created }}
      server-tag-name: ${{ steps.release.outputs.server--tag_name }}
      keycloak-created: ${{ steps.release.outputs.keycloak--release_created }}
      keycloak-tag-name: ${{ steps.release.outputs.keycloak--tag_name }}
    steps:
      - name: 🗝 Get app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.EMMA_APP_ID }}
          private-key: ${{ secrets.EMMA_APP_PRIVATE_KEY }}

      - name: ✨ Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please/config.json
          manifest-file: release-please/manifest.json
          token: ${{ steps.app-token.outputs.token }}

  publish-server:
    name: 🐳 Publish server docker image
    runs-on: ubuntu-latest
    needs:
      - "release-please"
      - "build-server"
    if: needs.release-please.outputs.server-created
    permissions:
      contents: read
      packages: write
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: 🏞️ Setup environment
        uses: ./.github/actions/setup-environment
        with:
          dotnet: true
          docker: true

      - name: 🗝️ Login to container registry.
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Build and push docker image
        run: just target docker:publish

  publish-keycloak:
    name: 🐳 Publish keycloak docker image
    runs-on: ubuntu-latest
    needs:
      - "release-please"
    if: needs.release-please.outputs.keycloak-created
    permissions:
      contents: read
      packages: write
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: 🏞️ Setup environment
        uses: ./.github/actions/setup-environment
        with:
          dotnet: true
          docker: true

      - name: 🗝️ Login to container registry.
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Build and push docker image
        run: just target keycloak:publish

  release-draft:
    name: 📢 Turn release draft into full release
    runs-on: ubuntu-latest
    needs:
      - release-please
      - publish-server
      - publish-keycloak
    if: needs.release-please.outputs.created
    permissions:
      contents: write # For `gh` to edit release
    steps:
      - name: 🗝 Get app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.EMMA_APP_ID }}
          private-key: ${{ secrets.EMMA_APP_PRIVATE_KEY }}

      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - name: 🚂 Server
        if: needs.release-please.outputs.server-created
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: >
          gh release edit
          ${{ needs.release-please.outputs.server-tag-name }}
          --draft=false

      - name: 🕵️ Keycloak
        if: needs.release-please.outputs.keycloak-created
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: >
          gh release edit
          ${{ needs.release-please.outputs.keycloak-tag-name }}
          --draft=false
